### ISSUE TITLE
[Feat] 클래스룸 생성 기능 추가

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Lms-Server#2]
## 📝 Description
**무엇을?**
- 클래스룸 생성 기능 추가

**왜?**
- 학생을 관리하려면 그룹을 통해 관리해야하기 때문에

## ❗️Todo
- [x] 요청에 필요한 필드값 정의
- [x] 클래스룸 도메인 생성
- [x] 클래스룸 생성 uri 추가

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
![image](https://github.com/user-attachments/assets/68d14cc5-89a8-4187-969c-5c3d53f23d45)

요청에 필요한 필드값
- 그룹 id
- 그룹 이름
- 초대 링크
- 생성 일자
- 수정 일자
